require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.0'


target 'MusicAlarmApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work
    
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work.
    :flipper_configuration => FlipperConfiguration.enabled([
      'Flipper' => '0.125.0',
      'Flipper-Folly' => '2.6.10',
      'Flipper-RSocket' => '1.4.3',
      'Flipper-DoubleConversion' => '3.2.0'
    ]),
    :production => false, # depends on whether you're running in production mode
  )

  target 'MusicAlarmAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    # Fix for React Native 0.78+
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
